// Generated by CoffeeScript 2.4.1
(function() {
  var GenericServer, ScpServer, execSync;

  GenericServer = require("./generic");

  ({execSync} = require("child_process"));

  ScpServer = class ScpServer extends GenericServer {
    static install(flags) {
      var install_cmd, steamLogin;
      super.install(flags);
      steamLogin = `+login ${flags.config.steamUserName} ${flags.config.steamPassword}`;
      install_cmd = `steamcmd ${steamLogin} +force_install_dir ${flags.path} +app_update ${flags.config.appId} validate +quit`;
      if (flags.dryrun !== true) {
        return execSync(install_cmd);
      }
    }

  };

  module.exports = ScpServer;

}).call(this);

//# sourceMappingURL=scp.js.map
