// Generated by CoffeeScript 2.4.1
(function() {
  var Chalk, GameServer, MinecraftServer, RustServer, SdtdServer, SrcdsServer;

  Chalk = require("chalk");

  RustServer = require("./games/rust");

  SdtdServer = require("./games/sdtd");

  SrcdsServer = require("./games/srcds");

  MinecraftServer = require("./games/minecraft");

  GameServer = class GameServer {
    static install(flags) {
      switch (flags.config.meta.game) {
        case "minecraft":
          MinecraftServer.install(flags);
          break;
        case "rust":
          RustServer.install(flags);
          break;
        case "garrysmod":
          SrcdsServer.install(flags);
          break;
        case "tf":
          SrcdsServer.install(flags);
          break;
        case "sdtd":
          SdtdServer.install(flags);
          break;
        case "scp":
          SdtdServer.install(flags);
          break;
        default:
          console.warn("That game isn't supported yet");
      }
      return console.info(Chalk.green.bold(`Installation of ${flags.config.meta.game} complete! 🚀`));
    }

  };

  module.exports = GameServer;

}).call(this);

//# sourceMappingURL=server_builder.js.map
